
import java.util.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * Esta es una clase para la interfaz grafica con la que va a interactuar el usuario 
 * @author Lorenzo Pazos
 */
public class GUICalculadora extends javax.swing.JFrame {
   boolean prendido=false;
   
   
    public GUICalculadora() {
        initComponents();
    }
    
   /**
    * Metodo para encender la calculadora y habilitar los botones
    * @return boolean
    */
    
    public boolean Prendido(){
        BotonReset.setEnabled(true);
        AbreParentesis.setEnabled(true);
        CierraParentesis.setEnabled(true);
        Boton0.setEnabled(true);
        Boton1.setEnabled(true);
        Boton2.setEnabled(true);
        Boton3.setEnabled(true);
        Boton4.setEnabled(true);
        Boton5.setEnabled(true);
        Boton6.setEnabled(true);
        Boton7.setEnabled(true);
        Boton8.setEnabled(true);
        Boton9.setEnabled(true);
        BotonSuma.setEnabled(true);
        BotonResta.setEnabled(true);
        BotonMultiplicacion.setEnabled(true);
        BotonDivision.setEnabled(true);
        BotonExponente.setEnabled(true);
        BotonPi.setEnabled(true);
        BotonNegativo.setEnabled(true);
        BotonPuntoDecimal.setEnabled(true);
        BotonResultado.setEnabled(true);
        BotonBack.setEnabled(true);
        Pantalla.setText("");
        prendido=true;
        OnOff.setText("On");
         
         return prendido;
    }
    
    /**
     * Metodo para deshabilitar los botones y "apagar" la calculadora
     * @return boolean
     */

    public boolean Apagado(){
        
        BotonReset.setEnabled(false);
        AbreParentesis.setEnabled(false);
        CierraParentesis.setEnabled(false);
        Boton0.setEnabled(false);
        Boton1.setEnabled(false);
        Boton2.setEnabled(false);
        Boton3.setEnabled(false);
        Boton4.setEnabled(false);
        Boton5.setEnabled(false);
        Boton6.setEnabled(false);
        Boton7.setEnabled(false);
        Boton8.setEnabled(false);
        Boton9.setEnabled(false);
        BotonSuma.setEnabled(false);
        BotonResta.setEnabled(false);
        BotonMultiplicacion.setEnabled(false);
        BotonDivision.setEnabled(false);
        BotonExponente.setEnabled(false);
        BotonPi.setEnabled(false);
        BotonNegativo.setEnabled(false);
        BotonPuntoDecimal.setEnabled(false);
        BotonResultado.setEnabled(false);
        BotonBack.setEnabled(false);
        Pantalla.setText("");
        prendido=false;
        OnOff.setText("Off");
        
        return prendido;
    }
    
    /**
     * Metodo que reune todos los metodos hechos, los utiliza, y arroja un resultado 
     * para la operacion dada por el usuario
     * @param cadena
     * @return String resultado
     */
    
      public String resultado(String cadena) {
        StringBuilder sb = new StringBuilder();
        Calculadora calculadora = new Calculadora();
        Revisores revisor = new Revisores(cadena);
        ArrayList<String> a= new ArrayList<>(Arrays.asList("+","-","/","*","^"));
        boolean resp;
        resp= false;
        
        int i=0;
        //bucle solamente para determinar si es un numero solo y que no cambie el textArea
        while(i<a.size() && !resp){
            resp=cadena.contains(a.get(i));
             i++;   
        }
        
        if(resp){
            if(revisor.revSintaxis()){
                sb.append(calculadora.evaluaPosFija(calculadora.creadorPosfija(cadena)));
            }
            else
                sb.append("Math ERROR");
        }
        else
            sb.append(cadena);
        return sb.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloCalc = new javax.swing.JLabel();
        Pantalla = new javax.swing.JTextField();
        BotonPrendeApaga = new javax.swing.JButton();
        BotonReset = new javax.swing.JButton();
        Boton7 = new javax.swing.JButton();
        Boton0 = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();
        AbreParentesis = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        CierraParentesis = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        BotonMultiplicacion = new javax.swing.JButton();
        BotonPuntoDecimal = new javax.swing.JButton();
        BotonResultado = new javax.swing.JButton();
        BotonDivision = new javax.swing.JButton();
        BotonSuma = new javax.swing.JButton();
        BotonResta = new javax.swing.JButton();
        BotonPi = new javax.swing.JButton();
        BotonExponente = new javax.swing.JButton();
        BotonNegativo = new javax.swing.JButton();
        BotonBack = new javax.swing.JButton();
        OnOff = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloCalc.setText("Calculadora ED 2024");

        Pantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PantallaActionPerformed(evt);
            }
        });

        BotonPrendeApaga.setText("On/Off");
        BotonPrendeApaga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrendeApagaActionPerformed(evt);
            }
        });

        BotonReset.setText("AC");
        BotonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResetActionPerformed(evt);
            }
        });

        Boton7.setText("7");
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });

        Boton0.setText("0");
        Boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0ActionPerformed(evt);
            }
        });

        Boton4.setText("4");
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });

        Boton1.setText("1");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        AbreParentesis.setText("(");
        AbreParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbreParentesisActionPerformed(evt);
            }
        });

        Boton3.setText("3");
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });

        Boton8.setText("8");
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });

        Boton5.setText("5");
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });

        Boton2.setText("2");
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });

        CierraParentesis.setText(")");
        CierraParentesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CierraParentesisActionPerformed(evt);
            }
        });

        Boton9.setText("9");
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });

        Boton6.setText("6");
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });

        BotonMultiplicacion.setText("x");
        BotonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiplicacionActionPerformed(evt);
            }
        });

        BotonPuntoDecimal.setText(".");
        BotonPuntoDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPuntoDecimalActionPerformed(evt);
            }
        });

        BotonResultado.setText("=");
        BotonResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonResultadoActionPerformed(evt);
            }
        });

        BotonDivision.setText("/");
        BotonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDivisionActionPerformed(evt);
            }
        });

        BotonSuma.setText("+");
        BotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumaActionPerformed(evt);
            }
        });

        BotonResta.setText("-");
        BotonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestaActionPerformed(evt);
            }
        });

        BotonPi.setText("π");
        BotonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPiActionPerformed(evt);
            }
        });

        BotonExponente.setText("^");
        BotonExponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonExponenteActionPerformed(evt);
            }
        });

        BotonNegativo.setText("+/-");
        BotonNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNegativoActionPerformed(evt);
            }
        });

        BotonBack.setText("Delete");
        BotonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBackActionPerformed(evt);
            }
        });

        OnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnOffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BotonPuntoDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(BotonReset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AbreParentesis, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CierraParentesis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(7, 7, 7)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(Boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(BotonResta, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                            .addComponent(BotonMultiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonNegativo))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BotonSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BotonDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(BotonExponente, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                            .addComponent(BotonPi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonPrendeApaga, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OnOff, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TituloCalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonPrendeApaga, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OnOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonReset)
                    .addComponent(AbreParentesis)
                    .addComponent(CierraParentesis)
                    .addComponent(BotonDivision)
                    .addComponent(BotonPi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton7)
                    .addComponent(Boton8)
                    .addComponent(Boton9)
                    .addComponent(BotonSuma)
                    .addComponent(BotonExponente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton4)
                    .addComponent(Boton5)
                    .addComponent(Boton6)
                    .addComponent(BotonResta)
                    .addComponent(BotonNegativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton1)
                    .addComponent(Boton2)
                    .addComponent(Boton3)
                    .addComponent(BotonMultiplicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton0)
                    .addComponent(BotonPuntoDecimal)
                    .addComponent(BotonResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonBack)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaActionPerformed
     
    }//GEN-LAST:event_PantallaActionPerformed

    private void BotonPrendeApagaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrendeApagaActionPerformed
 if(prendido==false){
            Prendido();}
        else
            Apagado();  
    }//GEN-LAST:event_BotonPrendeApagaActionPerformed

    private void BotonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBackActionPerformed
  int length = Pantalla.getText().length();
        int newLength = Pantalla.getText().length() - 1;
        String op;
        
        if(length >= 1){
            StringBuilder sb = new StringBuilder(Pantalla.getText());
            sb.deleteCharAt(newLength);
            op = sb.toString();
            Pantalla.setText(op);
        }        
    }//GEN-LAST:event_BotonBackActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        Pantalla.setText(Pantalla.getText()+ "5");
    }//GEN-LAST:event_Boton5ActionPerformed

    private void BotonPuntoDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPuntoDecimalActionPerformed
        Pantalla.setText(Pantalla.getText()+ ".");
    }//GEN-LAST:event_BotonPuntoDecimalActionPerformed

    private void AbreParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbreParentesisActionPerformed
        Pantalla.setText(Pantalla.getText()+ "(");
    }//GEN-LAST:event_AbreParentesisActionPerformed

    private void CierraParentesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CierraParentesisActionPerformed
      Pantalla.setText(Pantalla.getText()+ ")");
    }//GEN-LAST:event_CierraParentesisActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
       Pantalla.setText(Pantalla.getText()+ "7");
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        Pantalla.setText(Pantalla.getText()+ "8");
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        Pantalla.setText(Pantalla.getText()+ "9");
    }//GEN-LAST:event_Boton9ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        Pantalla.setText(Pantalla.getText()+ "4");
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
       Pantalla.setText(Pantalla.getText()+ "6");
    }//GEN-LAST:event_Boton6ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        Pantalla.setText(Pantalla.getText()+ "1");
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        Pantalla.setText(Pantalla.getText()+ "2");
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
       Pantalla.setText(Pantalla.getText()+ "3");
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0ActionPerformed
       Pantalla.setText(Pantalla.getText()+ "0");
    }//GEN-LAST:event_Boton0ActionPerformed

    private void BotonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDivisionActionPerformed
        Pantalla.setText(Pantalla.getText()+ "/");
    }//GEN-LAST:event_BotonDivisionActionPerformed

    private void BotonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumaActionPerformed
        Pantalla.setText(Pantalla.getText()+ "+");
    }//GEN-LAST:event_BotonSumaActionPerformed

    private void BotonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestaActionPerformed
        Pantalla.setText(Pantalla.getText()+ "-");
    }//GEN-LAST:event_BotonRestaActionPerformed

    private void BotonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiplicacionActionPerformed
       Pantalla.setText(Pantalla.getText()+ "*");
    }//GEN-LAST:event_BotonMultiplicacionActionPerformed

    private void BotonResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResultadoActionPerformed
      
        Pantalla.setText(resultado(Pantalla.getText()));
    }//GEN-LAST:event_BotonResultadoActionPerformed

    private void BotonPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPiActionPerformed
       Pantalla.setText(Pantalla.getText()+ "3.141592");
    }//GEN-LAST:event_BotonPiActionPerformed

    private void BotonExponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonExponenteActionPerformed
        Pantalla.setText(Pantalla.getText()+ "^");
    }//GEN-LAST:event_BotonExponenteActionPerformed

    private void BotonNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNegativoActionPerformed
        Pantalla.setText(Pantalla.getText()+"(-");
    }//GEN-LAST:event_BotonNegativoActionPerformed

    private void BotonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonResetActionPerformed
        Pantalla.setText("");
    }//GEN-LAST:event_BotonResetActionPerformed

    private void OnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnOffActionPerformed
        
    }//GEN-LAST:event_OnOffActionPerformed

    /**
     * Main que corre la interfaz grafica
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AbreParentesis;
    private javax.swing.JButton Boton0;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonBack;
    private javax.swing.JButton BotonDivision;
    private javax.swing.JButton BotonExponente;
    private javax.swing.JButton BotonMultiplicacion;
    private javax.swing.JButton BotonNegativo;
    private javax.swing.JButton BotonPi;
    private javax.swing.JButton BotonPrendeApaga;
    private javax.swing.JButton BotonPuntoDecimal;
    private javax.swing.JButton BotonReset;
    private javax.swing.JButton BotonResta;
    private javax.swing.JButton BotonResultado;
    private javax.swing.JButton BotonSuma;
    private javax.swing.JButton CierraParentesis;
    private javax.swing.JTextField OnOff;
    private javax.swing.JTextField Pantalla;
    private javax.swing.JLabel TituloCalc;
    // End of variables declaration//GEN-END:variables
}
